### ISSUE TITLE
Not working with private repo 

### ISSUE THREAD

**Issue by ManfredRichthofen** [wovnep/tauri-update-server#1]
Hi this is not working with a private github repo as the dl returns a 404 am I missing a scope on the api.

**Comment by ManfredRichthofen** [comment]
I dont think I am missing perms as `curl -vLJO -H 'Authorization: API KEY' 'https://github.com/USER/REPO/releases/download/v1.0/APP_1.0_x64_en-US.msi.zip'` downloads the proper file

**Comment by wovnep** [comment]
Can you provide the endpoint url on `tauri.conf.json`. 

PS: Sorry for the late response, haven't been in here a while.

**Comment by ManfredRichthofen** [comment]
Sure the endpoint is https://update.duncanindustries.net/update?current_version={{current_version}}&target={{target}}&arch={{arch}}. The api scopes are correct so it might be a problem with how the headers are passed.  No worries if you don't get to it I can probably look at it sometime this week when I'm done traveling.

**Comment by wovnep** [comment]
I tested with your endpoint, and it's working fine for me. And your repo is on private.
![image](https://github.com/wovnep/tauri-update-server/assets/122073572/4bf8455f-c1d6-49f3-84f3-0b1368ec69fe)

**Comment by wovnep** [comment]
Wait a minute, you are talking about download not working right?. I'm so sorry I didn't get that the first time. I never tested this with a private repo, so I never encountered this issue. I will find a solution immediately.

**Comment by ManfredRichthofen** [comment]
No worries. Yeah it is specifically with the download.

**Comment by ManfredRichthofen** [comment]
After rereading the tauri docs (https://docs.rs/tauri/latest/tauri/updater/struct.UpdateBuilder.html#method.header) it looks like i can add a header though rust although it seems kind of limited i can probably get it to work

**Comment by wovnep** [comment]
Found a way to get the direct link in private repos 5b3173fcc0eb3748c72d9411488ba2de0e6321ee

**Comment by ManfredRichthofen** [comment]
Thanks for working on this I'm just letting you know that the URL returns null as you can see here https://update.duncanindustries.net/update?current_version=1.0.9&target=windows&arch=x86_64
